---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fio-exporter
  name: fio-exporter
spec:
  type: NodePort
  selector:
    app: fio-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9996
    targetPort: 9996
